### ISSUE TITLE
Bind helper RFC changes

### ISSUE THREAD

**Issue by Windvis** [Serabe/ember-bind-helper#18]
Since the v3 alfa release the [bind helper RFC](https://github.com/emberjs/rfcs/pull/470) has been changed. The helper has been renamed to `fn` and no longer provides any context binding functionality. 

Since a polyfill for the fn helper [already exists](https://github.com/rwjblue/ember-fn-helper-polyfill) and it is part of Ember since 3.11 I think it might be better to remove the deprecation notice in the readme?

Having a bind helper can still be useful for use cases that the `@action` decorator + `fn` don't cover. For ex. Calling methods on third party classes you don't control.

**Comment by Serabe** [comment]
Fixed. Thank you!
