### ISSUE TITLE
{{bind}} doesn't work with @arg objects

### ISSUE THREAD

**Issue by gossi** [Serabe/ember-bind-helper#6]
Hey,

looks like your `{{bind}}` helper is what the `{{action}}` helper should be and is the way to go, especially with sparkles and glimmer components. I made a test-case to see how future-proof it is. You can find the whole test case here: https://github.com/gossi/sparkles-test/

I found one problem while I was researching: It cannot handle `@arg` properly. This does not work:

```hbs
{{! src/ui/routes/application/template.hbs }}

<MyComponent @parent={{this}} />
```

```ts
import Controller from '@ember/controller';

export default class ApplicationController extends Controller {
  whoAmI() {
    console.log('whoami', this instanceof ApplicationController, this);
  }
}
```

This does **not** work:
```hbs
{{! src/ui/components/my-component/template.hbs }}

<button onclick={{bind @parent.whoAmI}}>Who Am I?</button>
```

This **works**:
```hbs
{{! src/ui/components/my-component/template.hbs }}

<button onclick={{bind @parent.whoAmI target=@parent}}>Who Am I?</button>
```

(In my test these are the components `bind-object-context` and `bind-object-context-with-target`)

From my far point of view, I'd say, it doesn't work correctly with `@arg` objects.

**Comment by Serabe** [comment]
I'll check tonight or tomorrow morning. Should be easy to fix. Let's hope I'm not wrong :P

**Comment by Serabe** [comment]
I'll do the release these weekend. Thank you for your issue!

**Comment by gossi** [comment]
Awesome. Pls ping here, so I can test my suite against the new release. Thank you so much :)

**Comment by Serabe** [comment]
@gossi [v0.3.2 out](https://github.com/Serabe/ember-bind-helper/releases/tag/v0.3.2)!

**Comment by gossi** [comment]
Wonderful. My test project is working showing green results all over the place :)

**Comment by Serabe** [comment]
Great!
